# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/pd/2024-CLP/01_guia_vhdl/18-cont-bcd-enable-sint/Fuentes/Arty-Z7-10-Master.xdc

# IP: ip/vio_0/vio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet
