webtalk_init -webtalk_dir C:/pd/2024-CLP/01_guia_vhdl/18-cont-bcd-enable-sint/Sintesis/13-bcd1seg.sim/sim_1/behav/xsim/xsim.dir/contBCD_Lento_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 16 20:48:55 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "de8eefdf-c3ca-4908-ace9-9fe06a707195" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6cdf83b26ca54f8bb95a40fd75f96b58" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i9-12900HX" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "600 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8912_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2801028216 -regid "" -xml C:/pd/2024-CLP/01_guia_vhdl/18-cont-bcd-enable-sint/Sintesis/13-bcd1seg.sim/sim_1/behav/xsim/xsim.dir/contBCD_Lento_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/pd/2024-CLP/01_guia_vhdl/18-cont-bcd-enable-sint/Sintesis/13-bcd1seg.sim/sim_1/behav/xsim/xsim.dir/contBCD_Lento_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/pd/2024-CLP/01_guia_vhdl/18-cont-bcd-enable-sint/Sintesis/13-bcd1seg.sim/sim_1/behav/xsim/xsim.dir/contBCD_Lento_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
